_cmf_tree_ui_view:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/view
    defaults:
        _controller: cmf_tree_ui.controller.tree:viewAction

_cmf_tree_ui_process:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/do
    defaults:
        _controller: cmf_tree_ui.controller.tree:processAction

_cmf_tree_ui_children:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/children/{cmf_tree_ui_node_id}
    defaults:
        _controller: cmf_tree_ui.controller.tree:processAction
        cmf_tree_ui_command: children
        cmf_tree_ui_node_id: /
    requirements: { cmf_tree_ui_node_id: .* }

_cmf_tree_ui_move:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/move/{cmf_tree_ui_node_id}
    defaults:
        _controller: cmf_tree_ui.controller.tree:processAction
        cmf_tree_ui_command: move
        # cmf_tree_ui_node_id
        # cmf_tree_ui_target_node_id
        # cmf_tree_ui_before
    requirements: { cmf_tree_ui_node_id: .* }

_cmf_tree_ui_delete:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/delete/{cmf_tree_ui_node_id}
    defaults:
        _controller: cmf_tree_ui.controller.tree:processAction
        cmf_tree_ui_command: delete
    requirements: { cmf_tree_ui_node_id: .* }

_cmf_tree_ui_rename:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/rename/{cmf_tree_ui_node_id}
    defaults:
        _controller: cmf_tree_ui.controller.tree:processAction
        cmf_tree_ui_command: rename
        # cmf_tree_ui_new_name
    requirements: { cmf_tree_ui_node_id: .* }

_cmf_tree_ui_create_html:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/create_html/{child_class_name}/near/{cmf_tree_ui_node_id}
    defaults:
        _controller: cmf_tree_ui.controller.tree:createHtmlAction
    requirements: 
        cmf_tree_ui_node_id: .*
        # mode: "[inside|before]"

_cmf_tree_ui_edit_html:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/edit_html/{cmf_tree_ui_node_id}
    defaults:
        _controller: cmf_tree_ui.controller.tree:editHtmlAction
    requirements: { cmf_tree_ui_node_id: .* }
