_cmf_tree_ui_view:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/view
    defaults:
        _controller: cmf_tree_ui.controller.tree:viewAction

_cmf_tree_ui_process:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/do
    defaults:
        _controller: cmf_tree_ui.controller.tree:processAction

_cmf_tree_ui_children:
    pattern: /_cmf_tree_ui/{cmf_tree_ui_tree_name}/children/{cmf_tree_ui_node_id}
    defaults:
        _controller: cmf_tree_ui.controller.tree:processAction
        cmf_tree_ui_command: children
        cmf_tree_ui_node_id: /
    requirements: { cmf_tree_ui_node_id: .* }
